semi: false
singleQuote: true
trailingComma: all
printWidth: 88

plugins:
  - '@prettier/plugin-xml'
  - '@trivago/prettier-plugin-sort-imports'

importOrder:
  - '^node:(.*)$' # builtin
  - '^(@[^\/]|[^\.@])(.*)$' # external
  - '.*' # local
importOrderSeparation: true
importOrderSortSpecifiers: true
